In [1]:
import tensorflow as tf

In [4]:
import tensorflow.keras.layers as L

In [2]:
tf.enable_eager_execution()

In [12]:
a = tf.ones(shape=(5,10,10))

In [5]:
bilstm = L.Bidirectional(L.LSTM(20, return_sequences = True, return_state = True))

In [13]:
c = bilstm(a)

In [17]:
b = tf.ones((30,40))

In [25]:
tf.transpose()

[<tf.Tensor: id=16236, shape=(5, 10, 40), dtype=float32, numpy=
 array([[[-0.11550728, -0.06621784,  0.06853733, ..., -0.3894928 ,
          -0.24827893, -0.13922927],
         [-0.17473723, -0.1175481 ,  0.1083961 , ..., -0.38648602,
          -0.24921604, -0.13358063],
         [-0.20353074, -0.15782799,  0.13098168, ..., -0.38225055,
          -0.25023797, -0.12644944],
         ...,
         [-0.23035969, -0.26665035,  0.15999106, ..., -0.30398783,
          -0.23759249, -0.05508412],
         [-0.23072988, -0.27771983,  0.16099395, ..., -0.25262302,
          -0.21379589, -0.03324917],
         [-0.2309015 , -0.28677094,  0.16161333, ..., -0.1621811 ,
          -0.15343918, -0.01300125]],
 
        [[-0.11550728, -0.06621784,  0.06853733, ..., -0.3894928 ,
          -0.24827893, -0.13922927],
         [-0.17473723, -0.1175481 ,  0.1083961 , ..., -0.38648602,
          -0.24921604, -0.13358063],
         [-0.20353074, -0.15782799,  0.13098168, ..., -0.38225055,
          -0.2502379

In [26]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])

In [31]:
d = c[0]

In [36]:
d.shape

TensorShape([Dimension(5), Dimension(10), Dimension(40)])

In [35]:
tf.transpose(d, perm = [0,2,1])

<tf.Tensor: id=16444, shape=(5, 40, 10), dtype=float32, numpy=
array([[[-0.11550728, -0.17473723, -0.20353074, ..., -0.23035969,
         -0.23072988, -0.2309015 ],
        [-0.06621784, -0.1175481 , -0.15782799, ..., -0.26665035,
         -0.27771983, -0.28677094],
        [ 0.06853733,  0.1083961 ,  0.13098168, ...,  0.15999106,
          0.16099395,  0.16161333],
        ...,
        [-0.3894928 , -0.38648602, -0.38225055, ..., -0.30398783,
         -0.25262302, -0.1621811 ],
        [-0.24827893, -0.24921604, -0.25023797, ..., -0.23759249,
         -0.21379589, -0.15343918],
        [-0.13922927, -0.13358063, -0.12644944, ..., -0.05508412,
         -0.03324917, -0.01300125]],

       [[-0.11550728, -0.17473723, -0.20353074, ..., -0.23035969,
         -0.23072988, -0.2309015 ],
        [-0.06621784, -0.1175481 , -0.15782799, ..., -0.26665035,
         -0.27771983, -0.28677094],
        [ 0.06853733,  0.1083961 ,  0.13098168, ...,  0.15999106,
          0.16099395,  0.16161333],
    

In [37]:
del x

In [ ]:
tf.transpose(d,)

In [46]:
tf.tensordot(b,d, axes=[[1], [1]])

TypeError: tensordot() missing 1 required positional argument: 'axes'

In [48]:
tf.transpose(tf.tensordot(b, tf.transpose(d, perm = [0,2,1]), axes=[[1],[1]]),[1,0,2])

<tf.Tensor: id=16551, shape=(5, 30, 10), dtype=float32, numpy=
array([[[-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
        [-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
        [-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
        ...,
        [-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
        [-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
        [-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075]],

       [[-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
        [-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
        [-1.1226988 , -1.1116607 , -1.0285264 , ..., -0.4881846 ,
         -0.3265352 , -0.08517075],
    

In [45]:
print(d.shape)
print(b.shape)

(5, 10, 40)
(30, 40)


In [39]:
tf.map_fn(lambda x: tf.matmul(x, tf.transpose(d, perm = [0,2,1])), b)

InvalidArgumentError: In[0] is not a matrix. Instead it has shape [40] [Op:MatMul] name: map/while/MatMul/

In [41]:
b.shape

TensorShape([Dimension(30), Dimension(40)])

In [25]:
i = tf.eye(10)

In [26]:
c = a-i

In [27]:
tf.norm(c, ord ='fro', axis = [-2,-1])

<tf.Tensor: id=97, shape=(5,), dtype=float32, numpy=array([9.486833, 9.486833, 9.486833, 9.486833, 9.486833], dtype=float32)>

In [19]:
inp = tf.ones(shape=(5,10,30))

In [21]:
tf.keras.layers.Dense(3000)(inp)

<tf.Tensor: id=71, shape=(5, 10, 3000), dtype=float32, numpy=
array([[[ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
        [ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
        [ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
        ...,
        [ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
        [ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
        [ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841]],

       [[ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
        [ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
        [ 0.1660248 , -0.00543641,  0.14170894, ...,  0.04541901,
          0.04321436, -0.21283841],
     

In [23]:
tf.keras.layers.Flatten()(inp)

<tf.Tensor: id=83, shape=(5, 300), dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>

In [ ]:
a = 

In [29]:
if not False:
    print(1)

1
